### ISSUE TITLE
Build Magento admin section for the configuration

### ISSUE THREAD

**Issue by toh82** [sitewards/magento-webappmanifest#2]
This is only about having an empty section within the magento admin, which shows the Title **Web-App Manifest Configuration**

---
- [x] open pull request
- [x] build xml for the admin view
- [x] build whatever else is needed

**Comment by PatrickKubica** [comment]
https://github.com/sitewards/magento-webappmanifest/pull/16

**Comment by PatrickKubica** [comment]
merged
